<?php
/** @var \Algolia\AlgoliaSearch\ViewModel\Recommend\Cart $block */
$viewModel = $block->getViewModel();
$recommendConfig = $viewModel->getAlgoliaRecommendConfiguration();
if (!empty($recommendConfig['enabledRelatedInCart']) || !empty($recommendConfig['enabledFBTInCart']) || !empty($recommendConfig['isTrendItemsEnabledInCartPage'])):
    $cartItems = $viewModel->getAllCartItems();
    ?>
    <div id="algoliaRecommend">
        <div id="frequentlyBoughtTogether" class="recommend-component"></div>
        <div id="relatedProducts" class="recommend-component"></div>
        <div id="trendItems" class="trendsItem recommend-component"></div>
        <div id="lookingSimilar" class="lookingSimilar recommend-component"></div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/recommend" : {
                    "objectIDs" : <?= json_encode($cartItems) ?>
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>
