<?php
/** @var \Algolia\AlgoliaSearch\ViewModel\Recommend\ProductView $block */
$viewModel = $block->getViewModel();
$recommendConfig =  $viewModel->getAlgoliaRecommendConfiguration();

if (!empty($recommendConfig['enabledFBT']) || !empty($recommendConfig['enabledRelated']) || !empty($recommendConfig['isTrendItemsEnabledInPDP'])):
    $product = $viewModel->getProduct(); ?>
    <div id="frequentlyBoughtTogether" class="recommend-component"></div>
    <div id="relatedProducts" class="recommend-component"></div>
    <div id="trendItems" class="trendsItem recommend-component"></div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/recommend" : {
                    "algoliObjectId" : ["<?= $product->getId() ?>"]
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>
