<?php
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 */
$parentBlock = $block->getParentBlock();
$product = $parentBlock->getData('product');
?>
<div id="trendItems" class="trendsItem recommend-component"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Algolia_AlgoliaSearch/recommend" : {
                "algoliObjectId" : ["<?= $product->getId() ?>"]
            }
        },
        "[data-role=tocart-form]": {
            "catalogAddToCart": {}
        }
    }
</script>
