<?php

/** @var \Algolia\AlgoliaSearch\Block\Configuration $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$configuration = $block->getConfiguration();

?>

<?php
if ($configuration['instant']['enabled'] === true && $configuration['isSearchPage'] === true)  {
    $css = /* @noEscape */ $secureRenderer->renderTag('style', [],  $configuration['instant']['selector'] . ' {display:none}', false);
    /* @noEscape */ echo $secureRenderer->renderTag('script', [], 'document.write(\'' . $css . '\');' , false);
}
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], "window.algoliaConfig = " . json_encode($configuration) . ';' , false); ?>

